### ISSUE TITLE
Refactor Discussion

### ISSUE THREAD

**Issue by guyboertje** [musicglue/mongoid-slug#1]
Use case:

We are using UUIDs and not BSON Ids.
Our Model has a name, and once named can only be changed by admin.
The user can try to modify their slug if they dont like the one generated. So the sluggable field is not the name field but rather a secondary field called 'user_supplied_slug' and the generated slug is driven off of that.  The slug options declares a reference to the name field.
Names can have digits at the end.
So, the first "Jackson 5" gets jackson-5 and the second "Jackson 5" will get jackson-5-1 not jackson-6 or jackson-5-6.
We will not need to interpret a slug as an ID so we will always use find_by_slug! if the parameter does not match a UUID regex. So we dont need to add a counter if the proposed slug 'looks as if it could be an id'.
We will not want to transfer a slug from history - any historic slugs may still point to a resource.

Our model

``` ruby
  field :name
  field :user_supplied_slug

  slug :user_supplied_slug, history: true, reference: :name, skip_id_check: true, transfer_historic: false
```

We also need to do a 'Is this name (and slug) taken' ajax call from the browser.

On the server side we can do:

``` ruby
Mongoid::Slug::UniqueSlug.new(ModelClass.new).find_unique "Some Name"
```

which will return 'some-name' if the name is unique or 'some-name-n' if its not.

**Comment by digitalplaywright** [comment]
I understand the motivating example and it gives a good reason for refactoring. These are my suggestions after reviewing the code changes:
1. I never really liked the transfer historic slug functionality. It is unintuitive and breaks the concept of an id (the slug is really just an alternate id). I suggest removing the functionality instead, then the transfer_historic option is not needed and Mongoid Slug will act in the way you expect it to. 
2. The functionality that generates a custom slug based on :name or :user_supplied_slug seems overly complicated, and we created the custom slug builder for this purpose. I suggest removing the reference functionality and instead use the existing custom slug builder functionality, like e.g:
   
   ```
   slug do |cur_object|
     #put custom logic for generating url based upon :name or :user_supplied_slug here
     #should return a string that will be used to find a unique slug. See default_url_builder
     #in slug.rb for how this is done by default.
   end
   ```
3. Code style: small functions that are used one or two times should be inlined
   - https://github.com/musicglue/mongoid-slug/commit/fc6cbac492450211c33abd12f57ced3190840926
     (e.g appended?, append_attempt, next_counter)

@astjohn: What do you think?

@guyboertje Please let me know if you agree with the suggested changes.

**Comment by guyboertje** [comment]
1) +1 on removing historic transfer

2) I will try to revisit this.  The requirement stems from a marginal but plausible scenario.  The code has no way of knowing whether the -n is part of the base or part of the disambiguation.  I tried and failed to use the block mechanism but that was before I put in the skip_id_check bit which may have skewed my grasp of the situation.

Perhaps my understanding of the behaviour of the original codebase was being obscured because we use uuids (string id) so the possible-id check would pass and a -n would always be added.

3) Its my understanding that more smaller functions using descriptive names confers intent and follows long method refactoring guides.  However some methods are remnants of my refactoring and should be inlined.

**Comment by guyboertje** [comment]
RE point 2: if one removes the reference: :name part in the Entity model and runs the specs one can see the problem illustrated.

The second pelham 1 2 3 gets the slug pelham-1-2-3-4 and not pelham-1-2-3-1 because the sort sees the -3 as the last used value then increments and appends it to the attempt.

**Comment by astjohn** [comment]
@digitalplaywright, I love the direction this is heading in and totally agree with the suggestions made. I tend to disagree with point 3 somewhat depending on the context. I like small functions because they become easier to isolate while testing.

**Comment by guyboertje** [comment]
I too, feel that small functions make stubbing easier - but primarily small functions because it makes for self describing code.

**Comment by digitalplaywright** [comment]
RE point 2: That sounds like a problem with the algorithm that suggests slugs and should be solved there instead. I may be wrong, but I would believe next_counter is to blame for this and not the sort. The regular expression in next_counter should match on the first integer after the slug, and not on the slug itself since the slug may contain a number.

**Comment by guyboertje** [comment]
On a terminology note lets agree that there is an invariant part of the slug - the base, and a variant part - the bit added to create a unique slug.

The regex cant tell if the last dash digit in a string is from the invariant or variant part.

Which is why in the counter_sort method I try to lop of the invariant part and only sort on the variant parts, but the mechanism needs help to determine what the invariant part is.

**Comment by guyboertje** [comment]
Im thinking that there is an opportunity for a Sort class which is injected in by the implemetation. By default it is the regular one but I could substitute it with my own class via a mixin.  Then there would be no need for the reference option

I will protoytpe over the weekend.

**Comment by digitalplaywright** [comment]
@guyboertje I look forward to seeing your changes. Thank you for taking the lead on this. 

**Semantics of slug generation:** That the invariant part of the current slug is considered a variant when generating unique slugs is a bug. It should never do that. The behavior you suggest is the correct behavior and should replace the current behavior so I do not think we need a sort mixin (I may be wrong that we do not need a mixin):

```
The second pelham 1 2 3 should get the slug pelham-1-2-3-1.
```

To fix this problem I suggest removing the invariant part of the current slug from similar existing slugs of other documents before they are used to find unique slugs. This should fix the problem and require no other changes to the code. Please let me know what you think.

**Comment by guyboertje** [comment]
@digitalplaywright I think that will work.

**Comment by guyboertje** [comment]
@digitalplaywright - worked beautifully and simplifies the code.  Removes any need for reference option.

Have a look at the merge on this branch.  If you are happy I will send a pull request.

**Comment by digitalplaywright** [comment]
@guyboertje Looks good. That is a big improvement and makes the code much cleaner. :)

The only problem I see with the changes now is that the semantics of the new check_against_id option should probably be implemented in a different way. We check to see if a field is similar to BSON ObjectId for security reasons ( https://github.com/digitalplaywright/mongoid-slug/pull/91 ):

> If we allow users to input slugs that looks like the document id we may get all kinds of contingencies since we find by slug by default. E.g User A create a document with id "5032e126eccd310200000002", and user B created a document ?with slug "5032e126eccd310200000002". Which document is returned when we search for ?"5032e126eccd310200000002"?

However, as @al suggested in that thread, providing a basic implementation of the 'looks_like_slug?' method and making it easy for the user to override this method on a per class basis would probably solve the problem. 

When overriding 'looks_like_slug?' you can have it return what you desire, and then the check_against_id option is not necessary. This would also make it possible for users to define the behavior of 'looks_like_slug?' in cases like yours where the id is a UUID. Please let me know what you think.

**Comment by guyboertje** [comment]
@digitalplaywright I have implemented one proposal.  The problem I can see is each collection should provide a separate override if at all. While I was testing, trying to include a module with the override for the entity model but it overrode for all collections.  So I added a way of defining a 'slug_id_strategy' option on the id field that returns something that responds_to 'call'.

**Comment by digitalplaywright** [comment]
@guyboertje That makes sense. I think both of us would prefer that enabling users to define a strategy for looks_like_slug? was simpler. However, at the moment I can not think of a simpler solution considering the problems you mentioned. I will give it some more thought today and see if this complexity is necessary.

@al @astjohn I think this is closing in to the final solution so if you would like to provide feedback please let us know.

@iamnader This branch provides a solution to your problem in https://github.com/digitalplaywright/mongoid-slug/pull/91. Please let us know if this solution works for you.

**Comment by iamnader** [comment]
Yes, I think this would solve my issue

**Comment by digitalplaywright** [comment]
@guyboertje I think this is ready for a pull. Could you please submit a pull request for this work?

**Comment by guyboertje** [comment]
OK
